In [76]:
import os, sys
import requests
import pandas as pd
import matplotlib
import json
import django

from django.db import models
from polls.models import Asset
from polls.models import Transaction

In [77]:
os.chdir('/Users/MuriloMac/git/titan/django')

In [78]:
def all_assets(Asset):
    global all_asset_codes
    all_asset_codes = []
    all_assset_info = Asset.objects.all()
    for asset in all_assset_info:     
        all_asset_codes.append(asset.asset_code)

In [79]:
def call_historic_asset(asset_name):
    global time_series_asset_df
    time_series_asset_df
    ALPHA_KEY = os.environ['ALPHA_KEY']
    payload = {'symbol':asset_name,'function':'TIME_SERIES_DAILY_ADJUSTED', 'outputsize':'full', 'apikey':ALPHA_KEY}
    api_response = requests.get('https://www.alphavantage.co/query?', params=payload)
    text_json_values = api_response.json()['Time Series (Daily)']
    time_series_asset_df = pd.DataFrame.from_dict(text_json_values, orient='index')

In [80]:
all_assets(Asset)
call_historic_asset('GGBR4.SA')

In [81]:
all_asset_codes

['SUZB5',
 'ITSA2',
 'ABTT34',
 'ABBV34',
 'ABCB10',
 'ABCB4',
 'ACNB34',
 'EALT3',
 'EALT4',
 'ADHM3',
 'AELP3',
 'TIET3',
 'TIET4',
 'TIET11',
 'AETB34',
 'AFLT3',
 'ANDG3B',
 'ANDG4B',
 'CANT3B',
 'CANT4B',
 'AIGB34',
 'ALEF3B',
 'BRGE3',
 'BRGE5',
 'BRGE6',
 'BRGE7',
 'BRGE8',
 'BRGE11',
 'BRGE12',
 'CRIV3',
 'CRIV4',
 'RPAD3',
 'RPAD5',
 'RPAD6',
 'BRIV3',
 'BRIV4',
 'ALSC3',
 'APTI3',
 'APTI4',
 'FRRN3B',
 'FRRN5B',
 'FRRN6B',
 'AALR3',
 'ALPA3',
 'ALPA4',
 'GOGL35',
 'GOGL34',
 'ALUP3',
 'ALUP4',
 'ALUP11',
 'AMZO34',
 'BAZA3',
 'ABEV3',
 'AALL34',
 'AXPB34',
 'AMGN34',
 'CBEE3',
 'ANIM3',
 'AAPL34',
 'ARMT34',
 'ARNC34',
 'ARZZ3',
 'ATOM3',
 'ATTB34',
 'AVON34',
 'AZEV3',
 'AZEV4',
 'AZUL4',
 'BTOW3',
 'BVMF3',
 'BAHI3',
 'BPAN10',
 'BPAN4',
 'BGIP3',
 'BGIP4',
 'BEES3',
 'BEES4',
 'BOAC34',
 'BPAR3',
 'BRSR3',
 'BRSR5',
 'BRSR6',
 'BSAN33',
 'BDLL3',
 'BDLL4',
 'BTTL3',
 'BTTL4',
 'BALM3',
 'BALM4',
 'BBSE3',
 'BDRU11',
 'BDRX11',
 'BERK34',
 'BBYY34',
 'BETP3B',
 'BMKS3',
 'BIIB34',
 'BIOM3',
 'BSEV3',
 'BLAK34',
 'BONY34',
 'BOEI34',
 'BOBR3',
 'BOBR4',
 'BNPA3B',
 'BOXP34',
 'BBRK3',
 'HCBR3',
 'BRIN3',
 'BRML3',
 'BPHA3',
 'BRPR3',
 'BBDC3',
 'BBDC4',
 'BRAP3',
 'BRAP4',
 'BBAS11',
 'BBAS3',
 'BBAS12',
 'AGRO3',
 'BRKM3',
 'BRKM5',
 'BRKM6',
 'BFRE11',
 'BFRE12',
 'BSLI3',
 'BSLI4',
 'BRFS3',
 'BMYB34',
 'BRQB3',
 'BPAC3',
 'BPAC5',
 'BPAC11',
 'CABI3B',
 'CACO3B',
 'CAIA3B',
 'CAMB3',
 'CAMB4',
 'CAML3',
 'CPTP3B',
 'CRFB3',
 'CASN3',
 'CASN4',
 'CATP34',
 'CCRO3',
 'CCXC3',
 'CEBR3',
 'CEBR5',
 'CEBR6',
 'CEDO3',
 'CEDO4',
 'CEED3',
 'CEED4',
 'EEEL3',
 'EEEL4',
 'CEGR3',
 'CLSC3',
 'CLSC4',
 'CLGN34',
 'GPAR3',
 'CELP3',
 'CELP5',
 'CELP6',
 'CELP7',
 'CEPE3',
 'CEPE5',
 'CEPE6',
 'RANI3',
 'RANI4',
 'ENMA3B',
 'ENMA5B',
 'ENMA6B',
 'MAPT3',
 'MAPT4',
 'CMIG3',
 'CMIG4',
 'CESP3',
 'CESP5',
 'CESP6',
 'CHKE34',
 'CHVX34',
 'HGTX3',
 'CIEL3',
 'CMSA3',
 'CMSA4',
 'CNSY3',
 'CSCO34',
 'CTGP34',
 'COCA34',
 'CEEB3',
 'CEEB5',
 'CEEB6',
 'COCE3',
 'COCE5',
 'COCE6',
 'CTSH34',
 'COLG34',
 'CMCS34',
 'CGAS3',
 'CGAS5',
 'CRTE3B',
 'CRTE5B',
 'CALI3',
 'CALI4',
 'CTAX3',
 'CSMG3',
 'CPLE3',
 'CPLE5',
 'CPLE6',
 'COPH34',
 'CORR3',
 'CORR4',
 'RLOG3',
 'CZLT33',
 'CSAN3',
 'CSRN3',
 'CSRN5',
 'CSRN6',
 'COWC34',
 'CTNM3',
 'CTNM4',
 'COTY34',
 'CPFE3',
 'CPRE3',
 'CRDE3',
 'CREM3',
 'CRPG5',
 'CRPG6',
 'CARD3',
 'CTCA9',
 'CTCA3',
 'CVCB3',
 'CVSH34',
 'CCPR3',
 'CYRE3',
 'DHER34',
 'DASA3',
 'DEAI34',
 'PNVL3',
 'PNVL4',
 'DIRR3',
 'DOHL3',
 'DOHL4',
 'DMMO3',
 'DTCY3',
 'DTCY4',
 'DAGB33',
 'DUKB34',
 'DTEX3',
 'EBAY34',
 'ECOR3',
 'ELEK3',
 'ELEK4',
 'EKTR3',
 'EKTR4',
 'ELET3',
 'ELET5',
 'ELET6',
 'ETRO3B',
 'LIPR3',
 'ELPL3',
 'EMAE3',
 'EMAE4',
 'EMBR3',
 'ECPR3',
 'ECPR4',
 'ENBR3',
 'ENMT3',
 'ENMT4',
 'ENGI3',
 'ENGI4',
 'ENGI11',
 'ENEV3',
 'EGIE3',
 'EQTL3',
 'ESTC3',
 'ESTR3',
 'ESTR4',
 'ETER3',
 'EUCA3',
 'EUCA4',
 'EVEN3',
 'BAUH3',
 'BAUH4',
 'ESRX34',
 'EXXO34',
 'EZTC3',
 'FBOK34',
 'FDXB34',
 'FMXB34',
 'VSPT3',
 'VSPT4',
 'FHER3',
 'FESA3',
 'FESA4',
 'FBMC3',
 'FBMC4',
 'FIBR3',
 'TAXA4',
 'TAXA5',
 'TAXA6',
 'TAXA1',
 'TAXA2',
 'TAXA3',
 'TAXA0',
 'FNCN3',
 'FSLR34',
 'FLRY3',
 'FDMO34',
 'FJTA3',
 'FJTA4',
 'FRAS3',
 'FCXO34',
 'FTRT3B',
 'GFSA3',
 'OPGM3B',
 'GPSI34',
 'GEOO34',
 'GDBR34',
 'GMCO34',
 'GSHP3',
 'GEPA3',
 'GEPA4',
 'GOAU3',
 'GOAU4',
 'GGBR3',
 'GGBR4',
 'GILD34',
 'GOLL4',
 'GSGI34',
 'GPRO34',
 'GPIV33',
 'GPCP3',
 'CGRA3',
 'CGRA4',
 'GRND3',
 'GRUC3',
 'GRUC6',
 'GUAR3',
 'GUAR4',
 'HBTS3',
 'HBTS5',
 'HBTS6',
 'HAGA3',
 'HAGA4',
 'HALI34',
 'HBOR3',
 'HETA3',
 'HETA4',
 'HSHY34',
 'HOME34',
 'HONB34',
 'HOOT3',
 'HOOT4',
 'HPQB34',
 'HYPE3',
 'IDIV11',
 'IBMB34',
 'IBOV11',
 'IBRA11',
 'IBXL11',
 'IBXX11',
 'ICO211',
 'ICON11',
 'IDNT3',
 'IEEX11',
 'IFNC11',
 'IGBR3',
 'IGNM11',
 'IGCT11',
 'IGCX11',
 'IGTA3',
 'PARD3',
 'IMAT11',
 'MEAL3',
 'IMOB11',
 'CATA3',
 'CATA4',
 'IFIX11',
 'ROMI3',
 'INDX11',
 'IDVL3',
 'IDVL4',
 'INEP3',
 'INEP4',
 'ITLC34',
 'IVPR3B',
 'IVPR4B',
 'FIGE3',
 'FIGE4',
 'MYPK3',
 'IRBR3',
 'ISEE11',
 'ITAG11',
 'SQRM3',
 'SQRM11',
 'ITSA3',
 'ITSA4',
 'ITEC3',
 'ITUB3',
 'ITUB4',
 'IVBX11',
 'JBDU3',
 'JBDU4',
 'JBSS3',
 'JCPC34',
 'JHSF3',
 'JFEN3',
 'JFEN9',
 'JNJB34',
 'JOPA3',
 'JOPA4',
 'JPMC34',
 'JSLG3',
 'CTKA3',
 'CTKA4',
 'KEPL3',
 'KMBB34',
 'KLBN3',
 'KLBN4',
 'KLBN11',
 'KHCB34',
 'KROT3',
 'LBRN34',
 'LLIS3',
 'LIGT3',
 'LILY34',
 'LINX3',
 'LTEL3B',
 'LTEL5B',
 'LTEL11B',
 'RENT3',
 'LCAM3',
 'LMTB34',
 'LOGN3',
 'LAME3',
 'LAME4',
 'LHER3',
 'LHER4',
 'AMAR3',
 'LREN3',
 'SPRT3B',
 'LPSB3',
 'LUPA3',
 'MDIA3',
 'MACY34',
 'MSRO3',
 'MGLU3',
 'MAGG3',
 'MGEL3',
 'MGEL4',
 'POMO3',
 'POMO4',
 'MRFG3',
 'MSCD34',
 'MCDC34',
 'MDTC34',
 'MSPA3',
 'MSPA4',
 'MEND3',
 'MEND5',
 'MEND6',
 'MNZC3B',
 'BMEB3',
 'BMEB9',
 'BMEB4',
 'MERC3',
 'MERC4',
 'BMIN3',
 'BMIN9',
 'BMIN4',
 'MRCK34',
 'MTIG3',
 'MTIG4',
 'LEVE3',
 'FRIO3',
 'MTSA3',
 'MTSA4',
 'METB34',
 'MSFT34',
 'MLCX11',
 'MILS3',
 'MMAQ3',
 'MMAQ4',
 'BEEF3',
 'MNPR3',
 'MMXM3',
 'MDLZ34',
 'MOAR3',
 'MSBR34',
 'MOSC34',
 'MOVI3',
 'MRSA3B',
 'MRSA5B',
 'MRSA6B',
 'MRVE3',
 'MULT3',
 'MPLU3',
 'MNDL3',
 'NAFG3',
 'NAFG4',
 'NATU3',
 'NFLX34',
 'NEWT3B',
 'NIKE34',
 'BNBR3',
 'NORD3',
 'NRTQ3',
 'NUTR3',
 'ODER3',
 'ODER4',
 'ODPV3',
 'OGXP3',
 'OIBR3',
 'OIBR4',
 'OMGE3',
 'OPHE3B',
 'ORCL34',
 'OSXB3',
 'OFSA3',
 'PCAR3',
 'PCAR4',
 'PATI3',
 'PATI4',
 'PEAB3',
 'PEAB4',
 'PMAM3',
 'BPAT33',
 'PDGR3',
 'PEPB34',
 'RPMG3',
 'BRDT3',
 'PETR3',
 'PETR4',
 'PRIO3',
 'PTNT3',
 'PTNT4',
 'PFIZ34',
 'PGCO34',
 'PINE3',
 'PINE4',
 'PLAS3',
 'PPAR3',
 'FRTA3',
 'PSSA3',
 'PTBL3',
 'POSI3',
 'PFRM3',
 'PFRM9',
 'PRMN3B',
 'PRPT3B',
 'PRML3',
 'QGEP3',
 'QCOM34',
 'QUAL3',
 'QUSW3',
 'RADL3',
 'RAPT3',
 'RAPT4',
 'RCSL3',
 'RCSL4',
 'REDE3',
 'RNEW3',
 'RNEW4',
 'RNEW11',
 'OPRE3B',
 'RSUL3',
 'RSUL4',
 'RDNI3',
 'ROST34',
 'RSID3',
 'RAIL3',
 'SBSP3',
 'SSFO34',
 'SANC34',
 'SAPR3',
 'SAPR4',
 'SNSY3',
 'SNSY5',
 'SNSY6',
 'SANB3',
 'SANB4',
 'SANB11',
 'CTSA3',
 'CTSA4',
 'CTSA8',
 'STBP3',
 'SCAR3',
 'SMTO3',
 'SLED3',
 'SLED4',
 'PSEG3',
 'PSEG4',
 'SLBG34',
 'SHUL3',
 'SHUL4',
 'SCHW34',
 'CSAB3',
 'CSAB4',
 'SLCT3B',
 'SNSL3',
 'SEER3',
 'CSNA3',
 'SSBR3',
 'SLCE3',
 'SMLL11',
 'SMLS3',
 'SEDU3',
 'SOND3',
 'SOND5',
 'SOND6',
 'SPRI3',
 'SPRI5',
 'SPRI6',
 'SGPS3',
 'SPRN34',
 'AHEB3',
 'AHEB5',
 'AHEB6',
 'SBUB34',
 'STKF3',
 'OPSE3B',
 'OPTS3B',
 'SULA3',
 'SULA4',
 'SULA11',
 'NEMO3',
 'NEMO5',
 'NEMO6',
 'SUZB3',
 'TAEE3',
 'TAEE4',
 'TAEE11',
 'TGTB34',
 'TRPN3',
 'TECN3',
 'TCSA3',
 'TCNO3',
 'TCNO4',
 'TOYB3',
 'TOYB4',
 'TGMA3',
 'TEKA3',
 'TEKA4',
 'TKNO3',
 'TKNO4',
 'TELB3',
 'TELB4',
 'VIVT3',
 'VIVT4',
 'TLVT3B',
 'TEND3',
 'TESA3',
 'TSLA34',
 'TXRX3',
 'TXRX4',
 'TEXA34',
 'TMOS34',
 'TIFF34',
 'TIMP3',
 'SHOW3',
 'TWXB34',
 'TOTS3',
 'TRPL3',
 'TRPL4',
 'RIGG34',
 'TRVC34',
 'LUXM3',
 'LUXM4',
 'TRIS3',
 'TPIS3',
 'TUPY3',
 'TWTR34',
 'UBSG34',
 'UGPA3',
 'UCAS3',
 'UPAC34',
 'UNIP3',
 'UNIP5',
 'UNIP6',
 'UTEC34',
 'UPSS34',
 'UPKP3B',
 'USBC34',
 'USSX34',
 'USIM3',
 'USIM5',
 'USIM6',
 'UTIL11',
 'VALE3',
 'VLOE34',
 'VLID3',
 'VERZ34',
 'VVAR3',
 'VVAR4',
 'VVAR11',
 'VISA34',
 'VIVR3',
 'VULC3',
 'WALM34',
 'DISB34',
 'WEGE3',
 'WFCO34',
 'WUNI34',
 'MWET3',
 'MWET4',
 'WHRL3',
 'WHRL4',
 'WSON33',
 'WIZS3',
 'XRXB34']

In [83]:
cols = ['1. open','2. high','3. low','4. close','5. adjusted close','6. volume','7. dividend amount','8. split coefficient']
time_series_asset_df = time_series_asset_df[cols]
time_series_asset_df

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient
2000-05-02,2.4667,2.5556,2.4222,2.5556,1.2946,348659987,0.0000,1.0000
2000-05-03,2.5556,2.5556,2.4667,2.4667,1.2496,248039991,0.0000,1.0000
2000-05-04,2.4889,2.5111,2.4889,2.4889,1.2608,478529982,0.0000,1.0000
2000-05-05,2.4889,2.5556,2.4889,2.5333,1.2833,537029980,0.0000,1.0000
2000-05-08,2.5333,2.5333,2.4889,2.4889,1.2608,198899993,0.0000,1.0000
2000-05-09,2.4889,2.5111,2.3111,2.4000,1.2158,243359991,0.0000,1.0000
2000-05-10,2.3778,2.3778,2.2889,2.3111,1.1708,405989985,0.0000,1.0000
2000-05-11,2.2889,2.3333,2.2889,2.3333,1.1820,1092779960,0.0000,1.0000
2000-05-12,2.4444,2.4444,2.2444,2.2667,1.1483,420029985,0.0000,1.0000
2000-05-15,2.2889,2.2889,2.2667,2.2667,1.1483,3808349860,0.0000,1.0000
2000-05-16,2.2889,2.3333,2.2667,2.2889,1.1595,2303729915,0.0000,1.0000
2000-05-17,2.2889,2.2889,2.2222,2.2444,1.1370,170819994,0.0000,1.0000
2000-05-18,2.2222,2.2222,2.0889,2.1111,1.0694,1510469945,0.0000,1.0000
2000-05-19,2.0889,2.0889,2.0222,2.0444,1.0357,363869987,0.0000,1.0000
2000-05-22,2.0667,2.0667,1.9556,2.0000,1.0132,1219139955,0.0000,1.0000
2000-05-23,2.0000,2.0222,1.8889,1.9111,0.9681,1030769962,0.0000,1.0000
2000-05-24,1.9556,1.9556,1.8444,1.8889,0.9569,1700009938,0.0000,1.0000
2000-05-25,1.8889,1.9778,1.8889,1.9333,0.9794,3352049877,0.0000,1.0000
2000-05-26,1.9556,2.0444,1.9556,2.0444,1.0357,630629977,0.0000,1.0000
2000-05-29,2.1111,2.1111,2.0667,2.0889,1.0582,1043639962,0.0000,1.0000
2000-05-30,2.1111,2.2222,2.0889,2.2222,1.1257,3038489889,0.0000,1.0000
2000-05-31,2.2000,2.3333,2.2000,2.3333,1.1820,2719079900,0.0000,1.0000
2000-06-01,2.2889,2.4444,2.2889,2.4222,1.2271,1861469932,0.0000,1.0000
2000-06-02,2.4889,2.5111,2.3333,2.4000,1.2158,2189069920,0.0000,1.0000
2000-06-05,2.4444,2.4444,2.4000,2.4222,1.2271,1319759952,0.0000,1.0000
2000-06-06,2.4222,2.4222,2.4222,2.4222,1.2271,0,0.0000,1.0000
2000-06-07,2.4444,2.4667,2.4222,2.4667,1.2496,1031939962,0.0000,1.0000
2000-06-08,2.4889,2.5111,2.4000,2.4667,1.2496,1537379944,0.0000,1.0000
2000-06-09,2.4444,2.4667,2.4000,2.4444,1.2383,1205099956,0.0000,1.0000
2000-06-12,2.4000,2.4222,2.3556,2.3778,1.2045,405989985,0.0000,1.0000
...,...,...,...,...,...,...,...,...
2018-10-09,0.0000,0.0000,0.0000,0.0000,0.0000,0,0.0000,1.0000
2018-10-10,16.0300,16.2400,15.5100,15.5500,15.4183,14792200,0.0000,1.0000
2018-10-11,15.8400,15.9300,15.2600,15.7400,15.6067,16149600,0.0000,1.0000
2018-10-15,15.9500,16.0500,15.5300,15.5300,15.3985,14519000,0.0000,1.0000
2018-10-16,15.7500,16.2000,15.7500,16.2000,16.0628,12612300,0.0000,1.0000
2018-10-17,16.1000,16.2900,15.7900,16.1000,15.9636,9362200,0.0000,1.0000
2018-10-18,16.0800,16.0800,15.4700,15.4900,15.3588,12758200,0.0000,1.0000
2018-10-19,15.7000,15.7500,14.9700,15.1100,14.9820,17866500,0.0000,1.0000
2018-10-22,15.3800,15.8600,15.2600,15.7900,15.6563,14288000,0.0000,1.0000
2018-10-23,15.4800,15.7400,15.3000,15.6800,15.5472,13076900,0.0000,1.0000
2018-10-24,15.7200,15.9000,14.8300,14.9700,14.8432,16518300,0.0000,1.0000
2018-10-25,15.1100,15.5000,14.9700,15.3700,15.2398,10022500,0.0000,1.0000
2018-10-26,15.4100,15.7900,14.9900,15.7900,15.6563,22561600,0.0000,1.0000
2018-10-29,15.8100,15.9900,15.4300,15.6400,15.5075,16349200,0.0000,1.0000
2018-10-30,15.7500,16.0600,15.6000,15.8000,15.6662,17297500,0.0000,1.0000
2018-10-31,15.8700,16.2600,15.7000,16.2600,16.1223,31711800,0.0000,1.0000
2018-11-01,16.2800,16.7800,16.1600,16.4200,16.2809,33989600,0.0000,1.0000
2018-11-05,16.8100,17.3100,16.6600,16.9400,16.7965,25494900,0.0000,1.0000
2018-11-06,16.8000,17.1500,16.7100,16.9900,16.8461,12231400,0.0000,1.0000
2018-11-07,17.3600,17.4000,16.4500,16.5000,16.3603,19708600,0.0000,1.0000
2018-11-08,16.6500,16.8500,16.0800,16.0800,15.9438,13736000,0.0000,1.0000
2018-11-09,16.1400,16.3300,15.7900,16.1200,15.9835,10911300,0.0000,1.0000
2018-11-12,16.2400,16.2800,15.4100,15.4400,15.3092,12959700,0.0000,1.0000
2018-11-13,15.6000,15.6300,15.0200,15.2900,15.1605,14308900,0.0000,1.0000
2018-11-14,15.3000,15.3300,14.6400,15.1500,15.0217,18461100,0.0000,1.0000
2018-11-16,15.4000,16.2500,15.2300,16.2300,16.0925,16828200,0.0000,1.0000
2018-11-19,16.0700,16.4000,15.8700,16.1500,16.0132,12515500,0.0000,1.0000
2018-11-21,15.5800,15.8500,15.3000,15.3500,15.2200,15872300,0.0000,1.0000
2018-11-22,15.6500,15.6500,14.9800,15.3800,15.3800,9474000,0.0000,1.0000
2018-11-23,15.2600,15.2600,14.8300,14.9200,14.9200,11525100,0.0000,1.0000

In [82]:
Transaction.objects.all()

<QuerySet [<Transaction: Transaction object (1)>, <Transaction: Transaction object (2)>, <Transaction: Transaction object (3)>, <Transaction: Transaction object (4)>, <Transaction: Transaction object (5)>, <Transaction: Transaction object (6)>, <Transaction: Transaction object (7)>, <Transaction: Transaction object (8)>, <Transaction: Transaction object (9)>, <Transaction: Transaction object (10)>, <Transaction: Transaction object (11)>, <Transaction: Transaction object (12)>, <Transaction: Transaction object (13)>, <Transaction: Transaction object (14)>, <Transaction: Transaction object (15)>, <Transaction: Transaction object (16)>, <Transaction: Transaction object (17)>, <Transaction: Transaction object (18)>, <Transaction: Transaction object (19)>, <Transaction: Transaction object (20)>, '...(remaining elements truncated)...']>